Support Windows 10 and 11
On Windows 10/11 os.name is returned as `Windows 10` or `Windows 11`

Therefore the platform check fails with:
```
java.lang.IllegalStateException: Unsupported combination of OS/arch: Windows 11/amd64
        at com.bisnode.opa.configuration.OpaPlatform.getPlatform(OpaPlatform.java:46)
```